version: "3.8"

services:
    web:
        build: ./frontend
        ports:
            - 3002:3000
    api:
        build: ./backend
        ports:
            - 3005:3000
        volumes: 
            - ./backend/src:/app/src
    db:
        image: mongo:4.0-xenial
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/db
            - dbconfig:/data/configdb

volumes:
    dbdata:
    dbconfig:

networks:
    default:
        name: mern_net